### ISSUE TITLE
npm install  prettier prettier-plugin-awk npm ERR! code 1

### ISSUE THREAD

**Issue by lglgdouble** [Beaglefoot/prettier-plugin-awk#17]
[cyc@ayaoho myshell]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (GCC) 
[cyc@ayaoho myshell]$ 

[2022-10-28T05_55_31_962Z-debug-0.log](https://github.com/Beaglefoot/prettier-plugin-awk/files/9885645/2022-10-28T05_55_31_962Z-debug-0.log)

**Comment by Beaglefoot** [comment]
This is fixed in v0.2.3
