### ISSUE TITLE
prettier-plugin-awk breaks scientific notation

### ISSUE THREAD

**Issue by Popkornium18** [Beaglefoot/prettier-plugin-awk#19]
This awk program prints `1000000`:

```
BEGIN { print 1e6 }
```

However, prettier-plugin-awk formats it like this:

```
BEGIN { print 1 e6 }
```

When it is formatted like this, awk interprets it as an undefined variable `e6` and just prints `1`.

**Comment by Beaglefoot** [comment]
This is definitely a bug. As a workaround you can prepend block of code with `# prettier-ignore` comment.

**Comment by Beaglefoot** [comment]
Version 0.2.4 fixes the issue.
