### ISSUE TITLE
usage of "in" for multidimensional arrays causes crash

### ISSUE THREAD

**Issue by Popkornium18** [Beaglefoot/prettier-plugin-awk#20]
[This syntax](https://github.com/Beaglefoot/tree-sitter-awk/issues/12) causes prettier-plugin-awk to crash. Tree-sitter-awk should be upgraded to make prettier-plugin-awk parse this syntax correctly and actually format the file.

**Comment by Beaglefoot** [comment]
Fixed in v0.2.5
